### PR TITLE
added save/load to/from file for filter

### PR DESCRIPTION
**Pull request by glaslos**
Added Save and Load to the filter to write a filter to a file as gob and load it again. I had to export the fields in the CuckooFilter struct to make gob happy. Had to rename Count due to the Conflict with the function.

### CODE REVIEW

**Comment by glaslos** [comment]
Any chance to get this merged?

**Comment by weingart** [comment]
Possibly a better option would be to make *CuckooFilter meet the WriterTo and ReaderFrom interfaces instead: https://golang.org/pkg/io/#WriterTo

**Comment by seiflotfy** [comment]
great idea

**Comment by seiflotfy** [comment]
Added a more compact encode/decode

**Pull request closed without merging**
